### ISSUE TITLE
Difference between pusher-swift libraries?

### ISSUE THREAD

**Issue by sirvon** [pusher/pusher-platform-swift#6]
### What?

... What is the difference between this lib and this one called [pusher-websocket-swift](https://github.com/pusher/pusher-websocket-swift)?

### Suggested improvements

...

---- 

CC @pusher/sigsdk

**Comment by hamchapman** [comment]
You'll want to be using [pusher/pusher-websocket-swift](https://github.com/pusher/pusher-websocket-swift) for the time being 👍
